name: cross platform buil
on: [push, pull_request]
jobs:
    build-unix:
       runs-on: ubuntu-lates
       steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '23'
                cache: 'maven'
            - name: Build with Maven
              run: mvn -B clean package --file pom.xml
